import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import MobileNav from "../components/MobileNav";
import SideBar from "@/components/SideBar";
import NextNProgressBar from "@/components/NextNProgress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className='light'
    >
      <body
        style={{ fontFamily: "vazir" }}
        className={inter.className}
      >
        <Providers>
          <NextNProgressBar />
          <SideBar />
          {children}
          <MobileNav />
        </Providers>
      </body>
    </html>
  );
}
